### ISSUE TITLE
Can't move selected files to another folder

### ISSUE THREAD

**Issue by Sogl** [atom/tree-view#1033]
### Description

I found a bug when using file moving to another folder. When you select some files and move them with mouse, only first moved.

### Steps to Reproduce

1. Create new folder in Atom
2. Select more than one file with Shift keyboard key
3. Move selected files to new folder with mouse
3. Only the first file moved

How it looks:
![atom_move](https://cloud.githubusercontent.com/assets/7556290/22673366/d8d658fe-ed2d-11e6-9836-1f17c941dea0.gif)

As you can see, selection changed from 3 to 1 file after mouse drag.

**Expected behavior:** Move all selected files
**Actual behavior:** Only one file moved
**Reproduces how often:** 100%

Env:
Windows 7 x64
Atom 1.13.1 ia32
Tree-view 0.211.1

**Comment by 50Wliu** [comment]
Thanks for the issue!  I can reproduce this on Atom 1.15.0-dev-4eb3f22, Windows 10 x64.

**Comment by sergous** [comment]
In mac 10.12.3, atom 1.14.1:
1. selecting several files
2. start drug files group
3. only one file selected

**Comment by anderoonies** [comment]
hey!
i had a PR up that did this a good while ago
i'm going to rewrite it since the codebase has changed significantly since then

**Comment by 50Wliu** [comment]
Fixed by #1115.

**Comment by UziTech** [comment]
@50Wliu pull request #1115 doesn't seem to fix this problem

#793 is supposed to fix it but the author seems to be MIA

**Comment by Ben3eeE** [comment]
@UziTech Thank you :bowing_man: 

@anderoonies Are you still interested in rewriting that PR?

**Comment by mccallum-sgd** [comment]
Also still having this problem on Windows 10 Home x64 (ver: 1709, build: 16299.309).
Atom: 1.25.0
Tree-view: 0.221.3

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/tree-view/pull/1179

@UziTech Let me know if you think this should still be open for any reason 🙂 

@mccallum-sgd This will be available in a future Atom release. We have to fix the tests on master before including these changes in an Atom release /cc: https://github.com/atom/tree-view/issues/1203

**Comment by UziTech** [comment]
This was fixed by #1179

**Comment by mccallum-sgd** [comment]
Ah okay my mistake, thanks guys!
