### ISSUE TITLE
Atom crashes listing the contents of a directory with a large number of files

### ISSUE THREAD

**Issue by 50Wliu** [atom/tree-view#449]
_From @benbalter on May 14, 2015 18:59_

I'm not sure if it's possible to add in some sort of guard or max-file listing, but clicking expand on a folder with a large number of files and subfolders in it (1000s), renders Atom unresponsive. 

The unresponsiveness persists through a restart, as Atom tries to resume the previous state on load (thus expanding the folder again). I resolved the issue by deleting my `~/.atom/storage` folder, restarting, and resisting the urge to click the folder again.

### Steps to reproduce 

I don't know the exact number of files necessary, but here's an example of how to reproduce it:

1. Run [this script](https://github.com/benbalter/gman/blob/master/script/vendor-nl), which will wget a large website, creating a bunch of subdirectories
2. Open the parent folder in Atom
3. After a few moments (you don't need to wait for the script to stop)
4. Click the folder to expand it

## Expected

The folder would load displaying the sub tree, or at least part of it

## Actual

Editor has become unresponsive error

_Copied from original issue: atom/atom#6786_

**Comment by serapath** [comment]
I experience the same problem, especially when using `npm@3` which flattens all dependencies in `node_modules`. I think as soon as `npm@3` will be a mainstream thing, a lot of users will experience this problem.

**Comment by billybonks** [comment]
can you close this issue @50Wliu  i fixed it with a previous pr

**Comment by Joao-M-Almeida** [comment]
I still experience this issue when showing the contents of a folder with a large number of files (for me it happens with 170k files). Would it be possible to implement a prompt to warn the user ? similar to what atom does for large files? See: https://github.com/atom/atom/issues/10086

**Comment by billybonks** [comment]
ye, I have noticed it being slower as some of my folders grow in size, not
sure what the best solution is. I would like to view the files. how long
does it take to load 170k files?

**Comment by Joao-M-Almeida** [comment]
It just doesn't load this amount of files, it becomes unresponsive and after maybe one minute I get a popup saying the editor is not responding. 
One interesting thing is that the file finder works well even with this amount of files. I guess one solution would be just setting a threshold of number of files for which tree view would refuse to expand the folder.

**Comment by George3d6** [comment]
This still seems to be an issue, an it's quite annoying if you keep data in your project directory and just have the editor randomly crash if you have the misfortune of clicking that directory :/ (crashers for ~30k files on a rather alright machine)

Any idea if there's a fix for it that I'm unaware of ? Otherwise I might just try adding the warning prompt and making a pull req this friday.

**Comment by billybonks** [comment]
@George3d6 i doubt there is an active pr for this. i was thinking of creating one where the tree view will cache a sort and before resorting it will display the cache(if valid). Instead of me having to wait 4s every time i open a directory even though nothing has changed.

i think it would be good to get some benchmark numbers if possible before choosing a random limit

**Comment by Kalightortaio** [comment]
This is still an issue in 2019. It doesn't even have to be within one directory. When viewing subdirectories upon multiple folders in the tree view, Atom will become non responsive.

Attempts to allocate more resources to the program have all but failed in effectiveness of preventing. I can't count exactly at what the limit is, but it lies around having 300 - 400 directories/subdirectories open.
