### ISSUE TITLE
Tree view displays file as folder

### ISSUE THREAD

**Issue by mnquintana** [atom/tree-view#471]
_From @GameplayJDK on June 7, 2015 10:28_

I just updated to version `0.207.0` and found this:

![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/8023532/7f8e30fa-0d0f-11e5-829f-be2c20a013c5.png)

Somehow the `LAST_TODO` file (which is a file without an extension) is hows as a folder in my tree view. As such, I can't open it from there and need to use "File -> Open File..." to do so.
This also happens to other files (with extensions), as shown below:

![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/8023552/8f29bccc-0d10-11e5-8f11-3d7b0583bf76.png)

_Copied from original issue: atom/atom#7152_

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/tree-view?

**Comment by izuzak** [comment]
@GameplayJDK I'm having trouble reproducing this on Windows 8.1. Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) and if so -- can you share a ZIP of the folder you're able to reproduce this with? (Or, can you reproduce the problem by creating some folder structure manually and starting Atom)?

**Comment by GameplayJDK** [comment]
@izuzak

I'm currently not at home, but I'll check back as soon as possible.

I noticed, that I haven't added that this happened on an USB flash drive. I also haven't checked if this is reproducable on a normal SSD or HDD..

**Comment by GameplayJDK** [comment]
I checked it and this also happens in safe mode:

![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/8061329/8d60751e-0eca-11e5-8f96-7292cc239eca.png)

I also created a gif of how I used it:

![scap](https://cloud.githubusercontent.com/assets/4069263/8061387/deaef9c2-0eca-11e5-9105-813b531e387d.gif)

It seems that it doesn't have to do anything with the directory structure or the USB flash drive I mentioned.

**Comment by izuzak** [comment]
@GameplayJDK Thanks for the details and GIF. I'm still unable to reproduce this, however. Can you also clarify how you started Atom? Also, is this happening for all files or only some files? And if you use Atom 0.206.0 -- do you see the same issue? You can download that version from the releases page: https://github.com/atom/atom/releases

@kevinsawicki Any ideas about this one, or can you perhaps reproduce this?

**Comment by GameplayJDK** [comment]
I started it through the windows 8 search, e.g. I pressed the windows key, typed `atom` and hit enter. I used the mingw console from git for windows to start it atom in safe mode, e.g. I typed out `atom --safe`. I'm currently using linux for downloading android sdk packages, so I can't test the 0.206.0 now. But I'll test if this is only a windows related issue now and later when I use windows again I'll check out the 0.206.0.

**Comment by GameplayJDK** [comment]
Ok. (Sorry for the many messages)
On my Ubuntu 15.04 the 0.207.0 one, which I installed from the deb, does not show this weird behavior.

![screenshot from 2015-06-09 18 29 48](https://cloud.githubusercontent.com/assets/4069263/8063577/c3cec302-0ed5-11e5-9ebd-16c3b40c12b2.png)

**Comment by frankhale** [comment]
Atom 0.208 on Windows. Files being shown as folders in the treeview.

![atom-treeview-confusion](https://cloud.githubusercontent.com/assets/190154/8087898/8c971c22-0f6b-11e5-85fd-c1988dbacb90.png)

**Comment by GameplayJDK** [comment]
I just browsed a bit through the `.coffee` files and searched for some possible sources for this issue... I don't know how every bit of atom is related to one another, but I've found that it might be caused when the `createView()` method in `main.coffee` is called (after opening a file) and the returned `TreeView` is told to open a file (maybe using `add()`?). Could it be a problem caused by an is-file check returning the wrong value for a file?

I still haven't got to testing version 0.206.0 though

**Comment by audiophens** [comment]
+1

I'm seeing this behaviour in Windows 7 (64Bit) with the latest release (0.208) for the first time.

**Comment by izuzak** [comment]
Thanks for the reports everyone. Seeing this now as well on Atom 0.209.0-9771115 on Windows 8.1.

What I did:

1. cd into Atom's source folder
2. cd src
3. atom window.coffee

Not able to reproduce the problem on OSX with same steps.

cc @maxbrunsfeld @kevinsawicki for :eyes:

**Comment by Annonomus-Penguin** [comment]
Confirmed on Windows 8.1 0.209.0, also.

This actually seems to be an issue with Atom's open dialog, *not* tree-view.

I opened dev console, and typed in this command:

```javascript
> atom.project.rootDirectories[0].path
< "C:\Users\MyWindowsUsernameHere\Desktop\stuff.txt"
```

I think we ship this issue back over, personally. I'll look into this to see if I can't fix it on Atom itself.

**Comment by frankhale** [comment]
> This actually seems to be an issue with Atom's open dialog, not tree-view.

Just to clarify my case I almost never use the open dialog to open files. I just drag a file onto the Atom window. While dragging files seems to cause the tree-view to show the file as a folder the same is not true by dragging folders onto the Atom window. They will display fine in the tree-view.

**Comment by Annonomus-Penguin** [comment]
But Atom seems to use a common function for drag and drop and the dialog (from what I can tell).

**Comment by Annonomus-Penguin** [comment]
Ahh!

I disabled the tree-view package and the `atom.project.rootDirectories[0].path` command still returned the file, not the folder.

Unless I mad a wrong assumption here, this issue should be closed and the one on Atom should be reopened.

**Comment by GameplayJDK** [comment]
@Annonomus-Penguin However this still is just a windows related issue, as this could not be reproduced on either linux or mac.. So the origin of this issue possibly is hidden in some part of atom where platform specific code is used...

**Comment by Annonomus-Penguin** [comment]
@GameplayJDK I think the issue lies in the fact that Unix (that includes both Mac and Linux) and Windows filepaths are different.

Linux/Mac has this: `path/to/something`
Windows has this: `path\to\something` (opposite direction for slash)

I think that the code that removes the "top level" of the filepath (i.e. the `myfile.txt`) looks back to the last `/` and then takes off that and everything after that for the project. On Windows, this doesn't work, as there is no `/` in the path (you can't even use that character in the first place!)

Looking at the code, it looks like the have different menus for Windows/Linux/Mac, but I think the slash direction is the real issue here.

**Comment by Annonomus-Penguin** [comment]
Still, this issue should be closed because the issue lies in Atom itself, not tree-view

**Comment by frankhale** [comment]
No offense to anyone involved in the release process but I'm really disappointed that Atom 1.0 shipped with this bug

**Comment by LMLB** [comment]
I believe the root cause is that Atom's `DefaultDirectoryProvider` believes that windows paths are URLs (with the drive letter being the protocol) and therefore returns the "URL" unmodified.

**Comment by rugk** [comment]
From https://github.com/atom/tree-view/issues/605:

When I only open a few files (so no complete dir or repo) they show up the in the tree view. However the tree view displays them as directories and I cannot open them.
That's best to reproduce when you drag and drop these files into Atom.

Here is an example (executed in safe-mode):
![treeviewissue](https://cloud.githubusercontent.com/assets/11966684/10553357/4168c21a-745a-11e5-9ed2-f034d30ed2a5.gif)

Atom 1.0.19
Windows 7

**Comment by izuzak** [comment]
Another report in https://github.com/atom/tree-view/issues/632.

----

If I open a single file with Atom from a command line (atom some_file.cpp), it opens Atom, displays the current directory and its contents in the Tree View and displays the file which was passed as the argument.  So, everything works properly.

![bug1](https://cloud.githubusercontent.com/assets/5036152/10810884/facd443a-7dc2-11e5-8d81-806998dfc207.JPG)

However, if I open multiple files (atom some_file1.cpp some_file2.cpp some_file3.cpp), it opens Atom, display the files which were passed as the arguments, but does something strange in the Tree View:

![bug](https://cloud.githubusercontent.com/assets/5036152/10810846/5c05040a-7dc2-11e5-8e33-52c907fed9ef.JPG)

As you can see, instead of the current directory and its contents, it displays each file from the argument list as a directory.  However, they're all empty.  If I close the displayed files, there is no way to re-open them by clicking those empty directories.... they're just empty artifacts.  If I right click and show each of those directories in the explorer, it opens the proper current directory in the explorer.  If I right click and choose to open in the new window, it'll open a new instance of Atom with the selected file displaying and proper Tree View on the left.

Note that this only occurs if you are doing this with existing files.  If any of the arguments is a non-existing file, then you get a mixture of the two cases:

![bug2](https://cloud.githubusercontent.com/assets/5036152/10810930/a06015ee-7dc3-11e5-9a09-00e09f4c3127.JPG)

If all of the arguments are non-existing files, then proper Tree View is displayed, as none of the files actually exist, so they're just displayed and need to be saved.

I've tried this on two different machines and its the same result.  So, sounds like a bug.


Windows 7 SP1 & Windows 10
Atom 1.0.19

**Comment by Sogl** [comment]
Same in Atom 1.1.0 in Windows 7 x64.
![image](https://cloud.githubusercontent.com/assets/7556290/11106163/9eeb80a6-891f-11e5-84b1-7537be199e1e.png)

**Comment by 50Wliu** [comment]
Going to see if I can figure out where this is happening and if so, try to fix it.

No guarantees though, especially because I'm also pretty busy right now.

If anyone wants to work on this in the meantime, feel free - just because I'm assigned doesn't really mean anything :laughing:.

**Comment by benogle** [comment]
@50Wliu did you make any progress on this?

**Comment by 50Wliu** [comment]
Unfortunately not.  Had a lot of real-life things that I needed to get through :(.

**Comment by PaulAik** [comment]
I'm having a look into this, currently testing a fix.

It's actually related to a bug in core. I'll update with progress as I go... !

**Comment by benogle** [comment]
> I'm having a look into this, currently testing a fix.

:+1:

**Comment by J-qak** [comment]
@PaulAik Were you able to make any progress? I would be glad to assist, since this bug bothers me a lot.

**Comment by PaulAik** [comment]
I've got a solution that appears to fix it for me with no visible issues, but I'm having real trouble getting the test specs to run on either my Windows machine or my Mac.

I've opened an [issue](https://github.com/atom/atom/issues/10719) on the Atom repo to see if the team can help me out.

If I can't resolve the testing issue on my machine(s) then I'll do what I can locally and submit as a PR so the Atom CI environment can build & test.

**Comment by Ramsdenj** [comment]
This issue is happening to me using Arch Linux when I attempt to open a file using the open file dialog in a file browser.

**Comment by 50Wliu** [comment]
Fixed by atom/atom#10862, thanks a ton @PaulAik!  At the current pace of development the fix should be included starting in Atom 1.8.0.

**Comment by xrpweb** [comment]
TRy disable and enable tree-view package.

**Comment by Tarocch1** [comment]
This bug still appear in Atom 1.22.1 X64 in Windwos 10 .
![qq 20171211155257](https://user-images.githubusercontent.com/15124068/33820659-6d8260c0-de8b-11e7-8f29-adae47c4da1d.png)
single click get.js:
![qq 20171211155422](https://user-images.githubusercontent.com/15124068/33820712-9f5b837e-de8b-11e7-93ba-c4e946181a03.png)
double click get.js:
![qq 20171211155522](https://user-images.githubusercontent.com/15124068/33820729-b9822442-de8b-11e7-9628-350c4d84c7e8.png)
minimap plugin also disable in this file (folder??).

**Comment by rsese** [comment]
Thanks @Tarocch1 - if you can reproduce in safe mode, please open a new issue and fill out the issue template so we can take a look.

**Comment by Tico69man** [comment]
Sent from Yahoo Mail on Android 
 
  On Mon, Dec 11, 2017 at 2:58 PM, Robert Sese<notifications@github.com> wrote:   
Thanks @Tarocch1 - if you can reproduce in safe mode, please open a new issue and fill out the issue template so we can take a look.

**Comment by saurabh-gohil** [comment]
Facing the same issue in Atom 1.23.1 on Ubuntu 16.04. 
Any Fix?

**Comment by rsese** [comment]
@saurabh-gohil  if you can reproduce in safe mode, please open a new issue and fill out the issue template and we can take a look.

**Comment by siralb3rt** [comment]
I was having this issue with Atom 1.27.2.
Disabling file-icons solved the problem.
