### ISSUE TITLE
"The following file couldn't be moved to trash (is gvfs-trash installed?)" when attempting to delete empty nested folder with "Collapse direc

### ISSUE THREAD

**Issue by SlimeQ** [atom/tree-view#799]
![screenshot from 2016-04-08 17 21 42](https://cloud.githubusercontent.com/assets/3934698/14398008/d9b86574-fdae-11e5-8cdf-f2ba6e8d7bd2.png)

with "Collapse directories" enabled, deleting an empty nested directory fails

---
## ubuntu 14.04, atom 1.6.2

**update:** the first time attempting to delete `/1/2/3`, directory 3 is deleted but the tree is not updated. if the delete is attempted again the message above is shown. if the parent directory is collapsed and expanded again, it now shows `/1/2`. this process can be repeated until all directories are gone.

this seems somewhat related to #702

**Comment by mnzt** [comment]
Same error issue on arch linux:

```
Atom    : 1.7.2
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

 Kernel Release: 4.5.1-1-ARCH
OS: Arch Linux x86_64
```

**Comment by azat-io** [comment]
Same error 😞

**Comment by piecedigital** [comment]
So, like... is this a recent issue? This wasn't happening a few days ago. It worked right out the box, unlike the Windows version.

**Comment by 50Wliu** [comment]
Well, the notification was added in a recent release.  Before failing to delete a file would fail silently without an error message.
@mnzt, @azat-io, @piecedigital: are you all trying to delete a nested directory with "collapse directories" enabled?

**Comment by piecedigital** [comment]
@50Wliu I'm trying to delete several files in one directory, not even the directory itself.

**Comment by mnzt** [comment]
@50Wliu same story as @piecedigital. Even doing the following results in the error.
```
cd ~/
atom some.file
```
followed  by trying to delete `some.file`

**Comment by piecedigital** [comment]
Okay... I fixed my issue simply by changing the owner to myself.

Not sure how it changed in the first place...

**Comment by mnzt** [comment]
I still cannot delete _any_ file, even if owned by the user who launched atom

**Comment by 50Wliu** [comment]
Ok.  As this issue is talking specifically about deleting nested directories while "collapse empty directories" is enabled, can you please create a different issue?  Thanks!

**Comment by adnanzulkarnain** [comment]
Same error

**Comment by Thojad** [comment]
Same error on Elementary OS Freya...

**Comment by gauthier-delacroix** [comment]
Same error on Windows and Atom 1.8

**Comment by DoubleQuestionMark** [comment]
Same error on 16.04

**Comment by ctekhub** [comment]
Same on Kubuntu 14.04.

**Comment by evilxyz** [comment]
Same on Archlinux

**Comment by sumitkm** [comment]
It used to fail silently on Debian Jessie but now I see a red toast notification with the above error message.

**Comment by vinerz** [comment]
Same on Linux 15.10

**Comment by gswebspace** [comment]
Same on Ubuntu 16.04 LTS 64 Bit.
Atom v1.7.4

Tried deleting an empty sub-folder from the tree view on the left.
I am the owner of folder. Folder Permissions are currently set as "drwxrwsr-x".
Getting the same error on both cases when the sub-directory is collapsed or open (empty though) in the tree view.
![error](https://cloud.githubusercontent.com/assets/13507015/16414360/d1c09536-3d54-11e6-9253-d7242dc81664.png)


#### is gvfs-trash installed?
Tried to find the information about current version of 'gvfs' (or similar) packages using - 
`$ dpkg -l | grep 'gvfs' | awk '{print $2,$3}'`

Got this -
```
gvfs:amd64 1.28.2-1ubuntu1~16.04.1
gvfs-backends 1.28.2-1ubuntu1~16.04.1
gvfs-bin 1.28.2-1ubuntu1~16.04.1
gvfs-common 1.28.2-1ubuntu1~16.04.1
gvfs-daemons 1.28.2-1ubuntu1~16.04.1
gvfs-fuse 1.28.2-1ubuntu1~16.04.1
gvfs-libs:amd64 1.28.2-1ubuntu1~16.04.1
```
I was able to delete the folder using the usual 'Files' explorer but don't know why Atom is having problems.

**Comment by alice-em** [comment]
+1

**Comment by KieranMagisDev** [comment]
Same on Mint. Folder or file can be deleted from within the directory of Nemo though.

**Comment by azat-io** [comment]
It works good on Arch Linux, but not works on Ubuntu. Looks strange

**Comment by edgareler** [comment]
Hello everyone, I was having the same problem here and I found a solution for me (Ubuntu 16.04).

In my case the problem happened because the files were located in a different partition, and that partition didn't have a trash folder yet: `.Trash-1000/`. So, I had to create that folder in the root of the partition and give permissions to my user.

```shell
cd /media/youtPartition
sudo mkdir .Trash-1000
sudo chown -R yourUser:yourUser .Trash-1000/
```

You can first check if that is the case for you by trying to create and remove a file in the same folder with `gvfs-trash`:

```shell
cd /path/to/your/code
touch testFile
gvfs-trash testFile
```

If you have the same problem of me you will get an error like this: 

```
Error trashing file: Unable to find or create trash directory
```

**Comment by rzelnik** [comment]
Thank you @edgareler, I can confirm that it is working well that way for me. So the solution for the Atom project is:

1. rename the menu item from "Delete" to "Remove" or "Move to trash",
2. implement this feature: if trash does'nt exist, delete the file permanently.

**Comment by TipiT** [comment]
First: I think the right way to create the Trash folder is

`mkdir -p .Trash-1000/{expunged,files,info}`

Second: Did not work for me because I am running the projects located at /srv/www (owned by root) and using Vagrant so the files are not accessible for user running gvfs-trash from Atom.

Third: What did work is creating the Trash folder to root / and giving it my users rights. Like this:

`sudo mkdir -p /.Trash-1000/{expunged,files,info}
 sudo chown -R $USER:$USER .Trash-1000/`

**Comment by andibastian** [comment]
thankyou @edgareler, i tried your way in fedora 24 without first line (cd /media/yourPartition) :+1: 

sudo mkdir .Trash-1000
sudo chown -R yourUser:yourUser .Trash-1000/

and it works now.. :+1:

**Comment by jeyj0** [comment]
@TipiT's fix works for me, a solution by atom would be great though.

**Comment by macu** [comment]
`gvfs-trash` is installed. It would be helpful if the error message displayed in Atom instead said the trash folder is missing. In my case I'm working in `/var/www/...` Fixed by following @TipiT's instructions.

**Comment by virtuald** [comment]
When I run gvfs-trash manually, I get the following error on stdout:

```
Error trashing file: Unable to find or create trash directory
```

Perhaps atom should display that error?

**Comment by FRizZL** [comment]
The correct CMD (from @TipiT) is:
`sudo mkdir -p /.Trash-1000/{expunged,files,info}; sudo chown -R $USER:$USER /.Trash-1000/`

**Comment by suforoso** [comment]
My problem with `gvfs-trash` was about permission issues in Trash folder.

These steps on [askubuntu](- http://askubuntu.com/questions/636484/error-deleting-file-unable-to-find-or-create-wastebasket-directory-ubuntu-15-0) helped me to solve my problem:

**Comment by miguelcg** [comment]
Pull request #1008 opened for this issue, feel free to review it! :)

**Comment by miguelcg** [comment]
Pull request #1008 opened for this issue, feel free to review it! :)

**Comment by 50Wliu** [comment]
Fixed by #1008.

**Comment by brownman** [comment]
sudo mkdir -p $HOME/.Trash-1000/{expunged,files,info};
sudo chown -R $USER:$USER $HOME/.Trash-1000/

**Comment by tuf22191** [comment]
Hey guys, just giving my 2 cents here: I was able to delete files when opened atom via terminal. 
Step 1) sudo atom  (from terminal)
Step 2) Click File on top left and go to Open Folder...
Step 3) Open the directory/folder you would like and then you can see the files you want to delete and the deletion should work!

**Comment by jeyj0** [comment]
@tuf22191 While this is actually already mentioned somewhere here if I'm not mistaken, it should also be noted that running Atom with sudo is not a clever idea, since you can also cause a lot more harm to your system than simply delete what you planned to. If you feel comfortable with it, feel free to continue using it, but I advise against it.

**Comment by tuf22191** [comment]
@jeyj0 thanks for the advice (a little new to Linux)!

**Comment by mapasteper** [comment]
I got the same Issue and I found the solution in this blog
http://dev-notes.eu/2016/07/delete-files-in-atom-under-ubuntu-16-04/

**Comment by 50Wliu** [comment]
Because it appears that people are not reading this issue fully, I am locking it.

### Common solutions for this error
1. Make sure that `gvfs-trash` is installed
2. Make sure that a `.Trash-1000` folder exists - if it doesn't, try [these steps](https://github.com/atom/tree-view/issues/799#issuecomment-240025192)
3. Make sure that the file is not locked

If after those steps you are still unable to delete a file, please open a new issue and fill out the issue template.  Thanks!
